# Generated by Django 5.0.6 on 2024-06-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=255, unique=True)),
                ('park_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
